// <auto-generated />
using First_API.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace First_API.Migrations
{
    [DbContext(typeof(CustomDbContext))]
    [Migration("20240909224924_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("First_API.DataAccess.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepatmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            DepatmentName = " Department 1",
                            Description = "description1"
                        },
                        new
                        {
                            DepartmentId = 2,
                            DepatmentName = " Department 2",
                            Description = "description2"
                        },
                        new
                        {
                            DepartmentId = 3,
                            DepatmentName = " Department 3",
                            Description = "description3"
                        },
                        new
                        {
                            DepartmentId = 4,
                            DepatmentName = " Department 4",
                            Description = "description4"
                        },
                        new
                        {
                            DepartmentId = 5,
                            DepatmentName = " Department 5",
                            Description = "description5"
                        },
                        new
                        {
                            DepartmentId = 6,
                            DepatmentName = " Department 6",
                            Description = "description6"
                        },
                        new
                        {
                            DepartmentId = 7,
                            DepatmentName = " Department 7",
                            Description = "description7"
                        },
                        new
                        {
                            DepartmentId = 8,
                            DepatmentName = " Department 8",
                            Description = "description8"
                        });
                });

            modelBuilder.Entity("First_API.DataAccess.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            DepartmentId = 7,
                            Email = "emp1@mail.com",
                            EmpName = "emp name 1",
                            Salary = 28365
                        },
                        new
                        {
                            EmployeeId = 2,
                            DepartmentId = 6,
                            Email = "emp2@mail.com",
                            EmpName = "emp name 2",
                            Salary = 29995
                        },
                        new
                        {
                            EmployeeId = 3,
                            DepartmentId = 2,
                            Email = "emp3@mail.com",
                            EmpName = "emp name 3",
                            Salary = 28033
                        },
                        new
                        {
                            EmployeeId = 4,
                            DepartmentId = 1,
                            Email = "emp4@mail.com",
                            EmpName = "emp name 4",
                            Salary = 28865
                        },
                        new
                        {
                            EmployeeId = 5,
                            DepartmentId = 2,
                            Email = "emp5@mail.com",
                            EmpName = "emp name 5",
                            Salary = 26619
                        },
                        new
                        {
                            EmployeeId = 6,
                            DepartmentId = 2,
                            Email = "emp6@mail.com",
                            EmpName = "emp name 6",
                            Salary = 25598
                        },
                        new
                        {
                            EmployeeId = 7,
                            DepartmentId = 3,
                            Email = "emp7@mail.com",
                            EmpName = "emp name 7",
                            Salary = 25340
                        },
                        new
                        {
                            EmployeeId = 8,
                            DepartmentId = 7,
                            Email = "emp8@mail.com",
                            EmpName = "emp name 8",
                            Salary = 27119
                        },
                        new
                        {
                            EmployeeId = 9,
                            DepartmentId = 6,
                            Email = "emp9@mail.com",
                            EmpName = "emp name 9",
                            Salary = 25650
                        },
                        new
                        {
                            EmployeeId = 10,
                            DepartmentId = 7,
                            Email = "emp10@mail.com",
                            EmpName = "emp name 10",
                            Salary = 25618
                        },
                        new
                        {
                            EmployeeId = 11,
                            DepartmentId = 7,
                            Email = "emp11@mail.com",
                            EmpName = "emp name 11",
                            Salary = 26847
                        },
                        new
                        {
                            EmployeeId = 12,
                            DepartmentId = 4,
                            Email = "emp12@mail.com",
                            EmpName = "emp name 12",
                            Salary = 27439
                        },
                        new
                        {
                            EmployeeId = 13,
                            DepartmentId = 3,
                            Email = "emp13@mail.com",
                            EmpName = "emp name 13",
                            Salary = 27026
                        },
                        new
                        {
                            EmployeeId = 14,
                            DepartmentId = 4,
                            Email = "emp14@mail.com",
                            EmpName = "emp name 14",
                            Salary = 25737
                        },
                        new
                        {
                            EmployeeId = 15,
                            DepartmentId = 3,
                            Email = "emp15@mail.com",
                            EmpName = "emp name 15",
                            Salary = 28506
                        },
                        new
                        {
                            EmployeeId = 16,
                            DepartmentId = 4,
                            Email = "emp16@mail.com",
                            EmpName = "emp name 16",
                            Salary = 29914
                        },
                        new
                        {
                            EmployeeId = 17,
                            DepartmentId = 1,
                            Email = "emp17@mail.com",
                            EmpName = "emp name 17",
                            Salary = 26971
                        },
                        new
                        {
                            EmployeeId = 18,
                            DepartmentId = 6,
                            Email = "emp18@mail.com",
                            EmpName = "emp name 18",
                            Salary = 25809
                        },
                        new
                        {
                            EmployeeId = 19,
                            DepartmentId = 2,
                            Email = "emp19@mail.com",
                            EmpName = "emp name 19",
                            Salary = 27248
                        },
                        new
                        {
                            EmployeeId = 20,
                            DepartmentId = 5,
                            Email = "emp20@mail.com",
                            EmpName = "emp name 20",
                            Salary = 26584
                        },
                        new
                        {
                            EmployeeId = 21,
                            DepartmentId = 4,
                            Email = "emp21@mail.com",
                            EmpName = "emp name 21",
                            Salary = 29014
                        },
                        new
                        {
                            EmployeeId = 22,
                            DepartmentId = 1,
                            Email = "emp22@mail.com",
                            EmpName = "emp name 22",
                            Salary = 26343
                        },
                        new
                        {
                            EmployeeId = 23,
                            DepartmentId = 7,
                            Email = "emp23@mail.com",
                            EmpName = "emp name 23",
                            Salary = 28882
                        },
                        new
                        {
                            EmployeeId = 24,
                            DepartmentId = 5,
                            Email = "emp24@mail.com",
                            EmpName = "emp name 24",
                            Salary = 29460
                        },
                        new
                        {
                            EmployeeId = 25,
                            DepartmentId = 5,
                            Email = "emp25@mail.com",
                            EmpName = "emp name 25",
                            Salary = 29756
                        },
                        new
                        {
                            EmployeeId = 26,
                            DepartmentId = 2,
                            Email = "emp26@mail.com",
                            EmpName = "emp name 26",
                            Salary = 28959
                        },
                        new
                        {
                            EmployeeId = 27,
                            DepartmentId = 7,
                            Email = "emp27@mail.com",
                            EmpName = "emp name 27",
                            Salary = 28373
                        },
                        new
                        {
                            EmployeeId = 28,
                            DepartmentId = 3,
                            Email = "emp28@mail.com",
                            EmpName = "emp name 28",
                            Salary = 29964
                        },
                        new
                        {
                            EmployeeId = 29,
                            DepartmentId = 2,
                            Email = "emp29@mail.com",
                            EmpName = "emp name 29",
                            Salary = 26063
                        },
                        new
                        {
                            EmployeeId = 30,
                            DepartmentId = 7,
                            Email = "emp30@mail.com",
                            EmpName = "emp name 30",
                            Salary = 25339
                        },
                        new
                        {
                            EmployeeId = 31,
                            DepartmentId = 7,
                            Email = "emp31@mail.com",
                            EmpName = "emp name 31",
                            Salary = 25625
                        },
                        new
                        {
                            EmployeeId = 32,
                            DepartmentId = 6,
                            Email = "emp32@mail.com",
                            EmpName = "emp name 32",
                            Salary = 28619
                        },
                        new
                        {
                            EmployeeId = 33,
                            DepartmentId = 7,
                            Email = "emp33@mail.com",
                            EmpName = "emp name 33",
                            Salary = 26113
                        },
                        new
                        {
                            EmployeeId = 34,
                            DepartmentId = 7,
                            Email = "emp34@mail.com",
                            EmpName = "emp name 34",
                            Salary = 29928
                        },
                        new
                        {
                            EmployeeId = 35,
                            DepartmentId = 7,
                            Email = "emp35@mail.com",
                            EmpName = "emp name 35",
                            Salary = 27812
                        },
                        new
                        {
                            EmployeeId = 36,
                            DepartmentId = 5,
                            Email = "emp36@mail.com",
                            EmpName = "emp name 36",
                            Salary = 27575
                        },
                        new
                        {
                            EmployeeId = 37,
                            DepartmentId = 3,
                            Email = "emp37@mail.com",
                            EmpName = "emp name 37",
                            Salary = 26594
                        },
                        new
                        {
                            EmployeeId = 38,
                            DepartmentId = 6,
                            Email = "emp38@mail.com",
                            EmpName = "emp name 38",
                            Salary = 28210
                        },
                        new
                        {
                            EmployeeId = 39,
                            DepartmentId = 6,
                            Email = "emp39@mail.com",
                            EmpName = "emp name 39",
                            Salary = 27019
                        },
                        new
                        {
                            EmployeeId = 40,
                            DepartmentId = 6,
                            Email = "emp40@mail.com",
                            EmpName = "emp name 40",
                            Salary = 25224
                        },
                        new
                        {
                            EmployeeId = 41,
                            DepartmentId = 3,
                            Email = "emp41@mail.com",
                            EmpName = "emp name 41",
                            Salary = 28646
                        },
                        new
                        {
                            EmployeeId = 42,
                            DepartmentId = 1,
                            Email = "emp42@mail.com",
                            EmpName = "emp name 42",
                            Salary = 28146
                        },
                        new
                        {
                            EmployeeId = 43,
                            DepartmentId = 3,
                            Email = "emp43@mail.com",
                            EmpName = "emp name 43",
                            Salary = 25919
                        },
                        new
                        {
                            EmployeeId = 44,
                            DepartmentId = 6,
                            Email = "emp44@mail.com",
                            EmpName = "emp name 44",
                            Salary = 28759
                        },
                        new
                        {
                            EmployeeId = 45,
                            DepartmentId = 1,
                            Email = "emp45@mail.com",
                            EmpName = "emp name 45",
                            Salary = 29638
                        },
                        new
                        {
                            EmployeeId = 46,
                            DepartmentId = 7,
                            Email = "emp46@mail.com",
                            EmpName = "emp name 46",
                            Salary = 25495
                        },
                        new
                        {
                            EmployeeId = 47,
                            DepartmentId = 5,
                            Email = "emp47@mail.com",
                            EmpName = "emp name 47",
                            Salary = 26678
                        },
                        new
                        {
                            EmployeeId = 48,
                            DepartmentId = 2,
                            Email = "emp48@mail.com",
                            EmpName = "emp name 48",
                            Salary = 27118
                        },
                        new
                        {
                            EmployeeId = 49,
                            DepartmentId = 1,
                            Email = "emp49@mail.com",
                            EmpName = "emp name 49",
                            Salary = 29454
                        },
                        new
                        {
                            EmployeeId = 50,
                            DepartmentId = 1,
                            Email = "emp50@mail.com",
                            EmpName = "emp name 50",
                            Salary = 29556
                        },
                        new
                        {
                            EmployeeId = 51,
                            DepartmentId = 6,
                            Email = "emp51@mail.com",
                            EmpName = "emp name 51",
                            Salary = 29824
                        },
                        new
                        {
                            EmployeeId = 52,
                            DepartmentId = 6,
                            Email = "emp52@mail.com",
                            EmpName = "emp name 52",
                            Salary = 25714
                        },
                        new
                        {
                            EmployeeId = 53,
                            DepartmentId = 3,
                            Email = "emp53@mail.com",
                            EmpName = "emp name 53",
                            Salary = 29344
                        },
                        new
                        {
                            EmployeeId = 54,
                            DepartmentId = 7,
                            Email = "emp54@mail.com",
                            EmpName = "emp name 54",
                            Salary = 25595
                        },
                        new
                        {
                            EmployeeId = 55,
                            DepartmentId = 7,
                            Email = "emp55@mail.com",
                            EmpName = "emp name 55",
                            Salary = 29970
                        },
                        new
                        {
                            EmployeeId = 56,
                            DepartmentId = 3,
                            Email = "emp56@mail.com",
                            EmpName = "emp name 56",
                            Salary = 29027
                        },
                        new
                        {
                            EmployeeId = 57,
                            DepartmentId = 6,
                            Email = "emp57@mail.com",
                            EmpName = "emp name 57",
                            Salary = 26951
                        },
                        new
                        {
                            EmployeeId = 58,
                            DepartmentId = 1,
                            Email = "emp58@mail.com",
                            EmpName = "emp name 58",
                            Salary = 26743
                        },
                        new
                        {
                            EmployeeId = 59,
                            DepartmentId = 2,
                            Email = "emp59@mail.com",
                            EmpName = "emp name 59",
                            Salary = 29714
                        },
                        new
                        {
                            EmployeeId = 60,
                            DepartmentId = 4,
                            Email = "emp60@mail.com",
                            EmpName = "emp name 60",
                            Salary = 26077
                        },
                        new
                        {
                            EmployeeId = 61,
                            DepartmentId = 4,
                            Email = "emp61@mail.com",
                            EmpName = "emp name 61",
                            Salary = 29035
                        },
                        new
                        {
                            EmployeeId = 62,
                            DepartmentId = 2,
                            Email = "emp62@mail.com",
                            EmpName = "emp name 62",
                            Salary = 28118
                        },
                        new
                        {
                            EmployeeId = 63,
                            DepartmentId = 5,
                            Email = "emp63@mail.com",
                            EmpName = "emp name 63",
                            Salary = 25515
                        },
                        new
                        {
                            EmployeeId = 64,
                            DepartmentId = 5,
                            Email = "emp64@mail.com",
                            EmpName = "emp name 64",
                            Salary = 28815
                        },
                        new
                        {
                            EmployeeId = 65,
                            DepartmentId = 4,
                            Email = "emp65@mail.com",
                            EmpName = "emp name 65",
                            Salary = 26866
                        },
                        new
                        {
                            EmployeeId = 66,
                            DepartmentId = 7,
                            Email = "emp66@mail.com",
                            EmpName = "emp name 66",
                            Salary = 29102
                        },
                        new
                        {
                            EmployeeId = 67,
                            DepartmentId = 4,
                            Email = "emp67@mail.com",
                            EmpName = "emp name 67",
                            Salary = 26870
                        },
                        new
                        {
                            EmployeeId = 68,
                            DepartmentId = 7,
                            Email = "emp68@mail.com",
                            EmpName = "emp name 68",
                            Salary = 29840
                        },
                        new
                        {
                            EmployeeId = 69,
                            DepartmentId = 5,
                            Email = "emp69@mail.com",
                            EmpName = "emp name 69",
                            Salary = 25694
                        },
                        new
                        {
                            EmployeeId = 70,
                            DepartmentId = 6,
                            Email = "emp70@mail.com",
                            EmpName = "emp name 70",
                            Salary = 25590
                        },
                        new
                        {
                            EmployeeId = 71,
                            DepartmentId = 5,
                            Email = "emp71@mail.com",
                            EmpName = "emp name 71",
                            Salary = 25730
                        },
                        new
                        {
                            EmployeeId = 72,
                            DepartmentId = 2,
                            Email = "emp72@mail.com",
                            EmpName = "emp name 72",
                            Salary = 25137
                        },
                        new
                        {
                            EmployeeId = 73,
                            DepartmentId = 1,
                            Email = "emp73@mail.com",
                            EmpName = "emp name 73",
                            Salary = 28982
                        },
                        new
                        {
                            EmployeeId = 74,
                            DepartmentId = 2,
                            Email = "emp74@mail.com",
                            EmpName = "emp name 74",
                            Salary = 25843
                        },
                        new
                        {
                            EmployeeId = 75,
                            DepartmentId = 3,
                            Email = "emp75@mail.com",
                            EmpName = "emp name 75",
                            Salary = 29176
                        },
                        new
                        {
                            EmployeeId = 76,
                            DepartmentId = 4,
                            Email = "emp76@mail.com",
                            EmpName = "emp name 76",
                            Salary = 27998
                        },
                        new
                        {
                            EmployeeId = 77,
                            DepartmentId = 3,
                            Email = "emp77@mail.com",
                            EmpName = "emp name 77",
                            Salary = 27310
                        },
                        new
                        {
                            EmployeeId = 78,
                            DepartmentId = 6,
                            Email = "emp78@mail.com",
                            EmpName = "emp name 78",
                            Salary = 25608
                        },
                        new
                        {
                            EmployeeId = 79,
                            DepartmentId = 5,
                            Email = "emp79@mail.com",
                            EmpName = "emp name 79",
                            Salary = 26486
                        },
                        new
                        {
                            EmployeeId = 80,
                            DepartmentId = 2,
                            Email = "emp80@mail.com",
                            EmpName = "emp name 80",
                            Salary = 25062
                        },
                        new
                        {
                            EmployeeId = 81,
                            DepartmentId = 7,
                            Email = "emp81@mail.com",
                            EmpName = "emp name 81",
                            Salary = 27557
                        },
                        new
                        {
                            EmployeeId = 82,
                            DepartmentId = 5,
                            Email = "emp82@mail.com",
                            EmpName = "emp name 82",
                            Salary = 27369
                        },
                        new
                        {
                            EmployeeId = 83,
                            DepartmentId = 6,
                            Email = "emp83@mail.com",
                            EmpName = "emp name 83",
                            Salary = 29713
                        },
                        new
                        {
                            EmployeeId = 84,
                            DepartmentId = 1,
                            Email = "emp84@mail.com",
                            EmpName = "emp name 84",
                            Salary = 25611
                        },
                        new
                        {
                            EmployeeId = 85,
                            DepartmentId = 7,
                            Email = "emp85@mail.com",
                            EmpName = "emp name 85",
                            Salary = 25249
                        },
                        new
                        {
                            EmployeeId = 86,
                            DepartmentId = 1,
                            Email = "emp86@mail.com",
                            EmpName = "emp name 86",
                            Salary = 27628
                        },
                        new
                        {
                            EmployeeId = 87,
                            DepartmentId = 3,
                            Email = "emp87@mail.com",
                            EmpName = "emp name 87",
                            Salary = 28374
                        },
                        new
                        {
                            EmployeeId = 88,
                            DepartmentId = 1,
                            Email = "emp88@mail.com",
                            EmpName = "emp name 88",
                            Salary = 28384
                        },
                        new
                        {
                            EmployeeId = 89,
                            DepartmentId = 2,
                            Email = "emp89@mail.com",
                            EmpName = "emp name 89",
                            Salary = 28486
                        },
                        new
                        {
                            EmployeeId = 90,
                            DepartmentId = 2,
                            Email = "emp90@mail.com",
                            EmpName = "emp name 90",
                            Salary = 26238
                        },
                        new
                        {
                            EmployeeId = 91,
                            DepartmentId = 6,
                            Email = "emp91@mail.com",
                            EmpName = "emp name 91",
                            Salary = 29393
                        },
                        new
                        {
                            EmployeeId = 92,
                            DepartmentId = 2,
                            Email = "emp92@mail.com",
                            EmpName = "emp name 92",
                            Salary = 26355
                        },
                        new
                        {
                            EmployeeId = 93,
                            DepartmentId = 4,
                            Email = "emp93@mail.com",
                            EmpName = "emp name 93",
                            Salary = 26202
                        },
                        new
                        {
                            EmployeeId = 94,
                            DepartmentId = 7,
                            Email = "emp94@mail.com",
                            EmpName = "emp name 94",
                            Salary = 29888
                        },
                        new
                        {
                            EmployeeId = 95,
                            DepartmentId = 6,
                            Email = "emp95@mail.com",
                            EmpName = "emp name 95",
                            Salary = 29764
                        },
                        new
                        {
                            EmployeeId = 96,
                            DepartmentId = 2,
                            Email = "emp96@mail.com",
                            EmpName = "emp name 96",
                            Salary = 29194
                        },
                        new
                        {
                            EmployeeId = 97,
                            DepartmentId = 4,
                            Email = "emp97@mail.com",
                            EmpName = "emp name 97",
                            Salary = 26726
                        },
                        new
                        {
                            EmployeeId = 98,
                            DepartmentId = 2,
                            Email = "emp98@mail.com",
                            EmpName = "emp name 98",
                            Salary = 29857
                        },
                        new
                        {
                            EmployeeId = 99,
                            DepartmentId = 2,
                            Email = "emp99@mail.com",
                            EmpName = "emp name 99",
                            Salary = 28568
                        },
                        new
                        {
                            EmployeeId = 100,
                            DepartmentId = 5,
                            Email = "emp100@mail.com",
                            EmpName = "emp name 100",
                            Salary = 29824
                        },
                        new
                        {
                            EmployeeId = 101,
                            DepartmentId = 2,
                            Email = "emp101@mail.com",
                            EmpName = "emp name 101",
                            Salary = 26406
                        },
                        new
                        {
                            EmployeeId = 102,
                            DepartmentId = 5,
                            Email = "emp102@mail.com",
                            EmpName = "emp name 102",
                            Salary = 29309
                        },
                        new
                        {
                            EmployeeId = 103,
                            DepartmentId = 7,
                            Email = "emp103@mail.com",
                            EmpName = "emp name 103",
                            Salary = 27925
                        },
                        new
                        {
                            EmployeeId = 104,
                            DepartmentId = 5,
                            Email = "emp104@mail.com",
                            EmpName = "emp name 104",
                            Salary = 27749
                        },
                        new
                        {
                            EmployeeId = 105,
                            DepartmentId = 3,
                            Email = "emp105@mail.com",
                            EmpName = "emp name 105",
                            Salary = 27874
                        },
                        new
                        {
                            EmployeeId = 106,
                            DepartmentId = 1,
                            Email = "emp106@mail.com",
                            EmpName = "emp name 106",
                            Salary = 28078
                        },
                        new
                        {
                            EmployeeId = 107,
                            DepartmentId = 4,
                            Email = "emp107@mail.com",
                            EmpName = "emp name 107",
                            Salary = 26991
                        },
                        new
                        {
                            EmployeeId = 108,
                            DepartmentId = 7,
                            Email = "emp108@mail.com",
                            EmpName = "emp name 108",
                            Salary = 26153
                        },
                        new
                        {
                            EmployeeId = 109,
                            DepartmentId = 2,
                            Email = "emp109@mail.com",
                            EmpName = "emp name 109",
                            Salary = 28799
                        },
                        new
                        {
                            EmployeeId = 110,
                            DepartmentId = 5,
                            Email = "emp110@mail.com",
                            EmpName = "emp name 110",
                            Salary = 27356
                        },
                        new
                        {
                            EmployeeId = 111,
                            DepartmentId = 7,
                            Email = "emp111@mail.com",
                            EmpName = "emp name 111",
                            Salary = 26303
                        },
                        new
                        {
                            EmployeeId = 112,
                            DepartmentId = 5,
                            Email = "emp112@mail.com",
                            EmpName = "emp name 112",
                            Salary = 28673
                        },
                        new
                        {
                            EmployeeId = 113,
                            DepartmentId = 7,
                            Email = "emp113@mail.com",
                            EmpName = "emp name 113",
                            Salary = 26105
                        },
                        new
                        {
                            EmployeeId = 114,
                            DepartmentId = 7,
                            Email = "emp114@mail.com",
                            EmpName = "emp name 114",
                            Salary = 28553
                        },
                        new
                        {
                            EmployeeId = 115,
                            DepartmentId = 5,
                            Email = "emp115@mail.com",
                            EmpName = "emp name 115",
                            Salary = 27034
                        },
                        new
                        {
                            EmployeeId = 116,
                            DepartmentId = 4,
                            Email = "emp116@mail.com",
                            EmpName = "emp name 116",
                            Salary = 26605
                        },
                        new
                        {
                            EmployeeId = 117,
                            DepartmentId = 2,
                            Email = "emp117@mail.com",
                            EmpName = "emp name 117",
                            Salary = 27681
                        },
                        new
                        {
                            EmployeeId = 118,
                            DepartmentId = 4,
                            Email = "emp118@mail.com",
                            EmpName = "emp name 118",
                            Salary = 25299
                        },
                        new
                        {
                            EmployeeId = 119,
                            DepartmentId = 5,
                            Email = "emp119@mail.com",
                            EmpName = "emp name 119",
                            Salary = 26218
                        },
                        new
                        {
                            EmployeeId = 120,
                            DepartmentId = 5,
                            Email = "emp120@mail.com",
                            EmpName = "emp name 120",
                            Salary = 27081
                        },
                        new
                        {
                            EmployeeId = 121,
                            DepartmentId = 4,
                            Email = "emp121@mail.com",
                            EmpName = "emp name 121",
                            Salary = 28706
                        },
                        new
                        {
                            EmployeeId = 122,
                            DepartmentId = 2,
                            Email = "emp122@mail.com",
                            EmpName = "emp name 122",
                            Salary = 25342
                        },
                        new
                        {
                            EmployeeId = 123,
                            DepartmentId = 2,
                            Email = "emp123@mail.com",
                            EmpName = "emp name 123",
                            Salary = 26354
                        },
                        new
                        {
                            EmployeeId = 124,
                            DepartmentId = 3,
                            Email = "emp124@mail.com",
                            EmpName = "emp name 124",
                            Salary = 27587
                        },
                        new
                        {
                            EmployeeId = 125,
                            DepartmentId = 6,
                            Email = "emp125@mail.com",
                            EmpName = "emp name 125",
                            Salary = 25047
                        },
                        new
                        {
                            EmployeeId = 126,
                            DepartmentId = 1,
                            Email = "emp126@mail.com",
                            EmpName = "emp name 126",
                            Salary = 28997
                        },
                        new
                        {
                            EmployeeId = 127,
                            DepartmentId = 4,
                            Email = "emp127@mail.com",
                            EmpName = "emp name 127",
                            Salary = 25841
                        },
                        new
                        {
                            EmployeeId = 128,
                            DepartmentId = 6,
                            Email = "emp128@mail.com",
                            EmpName = "emp name 128",
                            Salary = 26219
                        },
                        new
                        {
                            EmployeeId = 129,
                            DepartmentId = 3,
                            Email = "emp129@mail.com",
                            EmpName = "emp name 129",
                            Salary = 27773
                        },
                        new
                        {
                            EmployeeId = 130,
                            DepartmentId = 1,
                            Email = "emp130@mail.com",
                            EmpName = "emp name 130",
                            Salary = 28878
                        },
                        new
                        {
                            EmployeeId = 131,
                            DepartmentId = 6,
                            Email = "emp131@mail.com",
                            EmpName = "emp name 131",
                            Salary = 25525
                        },
                        new
                        {
                            EmployeeId = 132,
                            DepartmentId = 6,
                            Email = "emp132@mail.com",
                            EmpName = "emp name 132",
                            Salary = 26528
                        },
                        new
                        {
                            EmployeeId = 133,
                            DepartmentId = 1,
                            Email = "emp133@mail.com",
                            EmpName = "emp name 133",
                            Salary = 27202
                        },
                        new
                        {
                            EmployeeId = 134,
                            DepartmentId = 2,
                            Email = "emp134@mail.com",
                            EmpName = "emp name 134",
                            Salary = 26793
                        },
                        new
                        {
                            EmployeeId = 135,
                            DepartmentId = 3,
                            Email = "emp135@mail.com",
                            EmpName = "emp name 135",
                            Salary = 27427
                        },
                        new
                        {
                            EmployeeId = 136,
                            DepartmentId = 2,
                            Email = "emp136@mail.com",
                            EmpName = "emp name 136",
                            Salary = 26638
                        },
                        new
                        {
                            EmployeeId = 137,
                            DepartmentId = 4,
                            Email = "emp137@mail.com",
                            EmpName = "emp name 137",
                            Salary = 27020
                        },
                        new
                        {
                            EmployeeId = 138,
                            DepartmentId = 3,
                            Email = "emp138@mail.com",
                            EmpName = "emp name 138",
                            Salary = 29130
                        },
                        new
                        {
                            EmployeeId = 139,
                            DepartmentId = 1,
                            Email = "emp139@mail.com",
                            EmpName = "emp name 139",
                            Salary = 25800
                        },
                        new
                        {
                            EmployeeId = 140,
                            DepartmentId = 5,
                            Email = "emp140@mail.com",
                            EmpName = "emp name 140",
                            Salary = 27440
                        },
                        new
                        {
                            EmployeeId = 141,
                            DepartmentId = 2,
                            Email = "emp141@mail.com",
                            EmpName = "emp name 141",
                            Salary = 25163
                        },
                        new
                        {
                            EmployeeId = 142,
                            DepartmentId = 7,
                            Email = "emp142@mail.com",
                            EmpName = "emp name 142",
                            Salary = 29521
                        },
                        new
                        {
                            EmployeeId = 143,
                            DepartmentId = 7,
                            Email = "emp143@mail.com",
                            EmpName = "emp name 143",
                            Salary = 25295
                        },
                        new
                        {
                            EmployeeId = 144,
                            DepartmentId = 3,
                            Email = "emp144@mail.com",
                            EmpName = "emp name 144",
                            Salary = 28333
                        },
                        new
                        {
                            EmployeeId = 145,
                            DepartmentId = 2,
                            Email = "emp145@mail.com",
                            EmpName = "emp name 145",
                            Salary = 26550
                        },
                        new
                        {
                            EmployeeId = 146,
                            DepartmentId = 3,
                            Email = "emp146@mail.com",
                            EmpName = "emp name 146",
                            Salary = 28737
                        },
                        new
                        {
                            EmployeeId = 147,
                            DepartmentId = 6,
                            Email = "emp147@mail.com",
                            EmpName = "emp name 147",
                            Salary = 27352
                        },
                        new
                        {
                            EmployeeId = 148,
                            DepartmentId = 4,
                            Email = "emp148@mail.com",
                            EmpName = "emp name 148",
                            Salary = 29752
                        },
                        new
                        {
                            EmployeeId = 149,
                            DepartmentId = 4,
                            Email = "emp149@mail.com",
                            EmpName = "emp name 149",
                            Salary = 29227
                        },
                        new
                        {
                            EmployeeId = 150,
                            DepartmentId = 2,
                            Email = "emp150@mail.com",
                            EmpName = "emp name 150",
                            Salary = 25182
                        },
                        new
                        {
                            EmployeeId = 151,
                            DepartmentId = 4,
                            Email = "emp151@mail.com",
                            EmpName = "emp name 151",
                            Salary = 28363
                        },
                        new
                        {
                            EmployeeId = 152,
                            DepartmentId = 5,
                            Email = "emp152@mail.com",
                            EmpName = "emp name 152",
                            Salary = 28439
                        },
                        new
                        {
                            EmployeeId = 153,
                            DepartmentId = 4,
                            Email = "emp153@mail.com",
                            EmpName = "emp name 153",
                            Salary = 26130
                        },
                        new
                        {
                            EmployeeId = 154,
                            DepartmentId = 6,
                            Email = "emp154@mail.com",
                            EmpName = "emp name 154",
                            Salary = 29845
                        },
                        new
                        {
                            EmployeeId = 155,
                            DepartmentId = 7,
                            Email = "emp155@mail.com",
                            EmpName = "emp name 155",
                            Salary = 26964
                        },
                        new
                        {
                            EmployeeId = 156,
                            DepartmentId = 6,
                            Email = "emp156@mail.com",
                            EmpName = "emp name 156",
                            Salary = 25118
                        },
                        new
                        {
                            EmployeeId = 157,
                            DepartmentId = 3,
                            Email = "emp157@mail.com",
                            EmpName = "emp name 157",
                            Salary = 27361
                        },
                        new
                        {
                            EmployeeId = 158,
                            DepartmentId = 2,
                            Email = "emp158@mail.com",
                            EmpName = "emp name 158",
                            Salary = 29041
                        },
                        new
                        {
                            EmployeeId = 159,
                            DepartmentId = 7,
                            Email = "emp159@mail.com",
                            EmpName = "emp name 159",
                            Salary = 29667
                        },
                        new
                        {
                            EmployeeId = 160,
                            DepartmentId = 5,
                            Email = "emp160@mail.com",
                            EmpName = "emp name 160",
                            Salary = 27375
                        },
                        new
                        {
                            EmployeeId = 161,
                            DepartmentId = 4,
                            Email = "emp161@mail.com",
                            EmpName = "emp name 161",
                            Salary = 27129
                        });
                });

            modelBuilder.Entity("First_API.DataAccess.Entities.Employee", b =>
                {
                    b.HasOne("First_API.DataAccess.Entities.Department", "Departments")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departments");
                });

            modelBuilder.Entity("First_API.DataAccess.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
